INSERT INTO answers (question_id, answer, isCorrect) VALUES (1, 'False', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (1, 'True', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (2, 'Toronto Raptors', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (2, 'Golden State Warriors', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (3, 'Houston Astros', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (3, 'Philadelphia Phillies', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (4, 'Argentina', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (4, 'France', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (5, '45 and 23', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (5, '22 and 56', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (6, 'Nobody, it was a stray cat', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (6, 'Don Corleone', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (7, '2', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (7, '0', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (8, '3', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (8, '5', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (9, 'Rush Hour', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (9, 'Rush Hour 2', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (10, 'Denzel Washington', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (10, 'Samuel L Jackson', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (11, 'Ottawa', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (11, 'Toronto', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (12, 'Russia', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (12, 'Canada', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (13, 'Vatican City', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (13, 'Malta', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (14, '54', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (14, '50', FALSE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (15, '10', TRUE);
INSERT INTO answers (question_id, answer, isCorrect) VALUES (15, '13', FALSE);


